### ISSUE TITLE
可否将原本的解析两个IP到一个域名改为一个，另一个留作备用，主IP挂掉切换为备用IP 

### ISSUE THREAD

**Issue by AstraeusZane** [yumusb/AutoChangeDns#2]
开发者您好，感谢你的贡献；目前我是有一个CF故障转移的需求，AutoChangeDns的功能与我的需求及其接近了；但唯一的区别在于我一个域名只需要对应一个IP，另一个是备用的。
所以想请教您，可否将原本的解析两个IP到一个域名改为一个，另一个留作备用，主IP挂掉切换为备用IP 这样？
非常感谢，已经在你的博客大赏了！

**Comment by yumusb** [comment]
别的先不说，你打赏的钱在哪里呢？

**Comment by 1030173840** [comment]
我和博客上的是一个人，因为不知道你平时在什么平台 所以两边都评论了

**Comment by 1030173840** [comment]
打赏了是在博客扫微信的付款码的，虽然少，但是囊中羞涩实在不好意思；如果问题解决了，我再继续打赏吧，非常感谢您的贡献！

**Comment by yumusb** [comment]
那你找错了。我博客没有介绍这个项目，也没有微信打赏。你应该找你打赏的那个博客去问。

**Comment by AstraeusZane** [comment]
好吧，看来是打赏转载项目的博客了，不过没事，我去你博客说的pinqiong.net打赏吧
然后就是希望大佬能赐教一下，因为CF的故障切换我已经研究很久了，但是因为太菜了不懂py，所以拜托了。
